/**
 * McBuleli Hackathon Kinshasa 2026 — photo gallery (R2).
 * Generated by scripts/upload-hackathon-gallery-r2.ts — do not edit by hand.
 */
export type HackathonGalleryPhoto = {
  id: string;
  batch: string;
  fileName: string;
  thumbUrl: string;
  hdUrl: string;
};

export const HACKATHON_GALLERY_PHOTOS: HackathonGalleryPhoto[] = [
  {
    "id": "batch-a-6c1b28a8",
    "batch": "batch-a",
    "fileName": "SILIKIN1.jpg",
    "thumbUrl": "https://pub-1c80c0f78d1d4fb2bbf1179753cdb92c.r2.dev/mcbuleli-community/hackathon/gallery/2026/batch-a/001-SILIKIN1-6c1b28a8.jpg",
    "hdUrl": "https://pub-1c80c0f78d1d4fb2bbf1179753cdb92c.r2.dev/mcbuleli-community/hackathon/gallery/2026/batch-a/001-SILIKIN1-6c1b28a8.jpg"
  },
  {
    "id": "batch-a-2015b2f1",
    "batch": "batch-a",
    "fileName": "SILIKIN10.jpg",
    "thumbUrl": "https://pub-1c80c0f78d1d4fb2bbf1179753cdb92c.r2.dev/mcbuleli-community/hackathon/gallery/2026/batch-a/002-SILIKIN10-2015b2f1.jpg",
    "hdUrl": "https://pub-1c80c0f78d1d4fb2bbf1179753cdb92c.r2.dev/mcbuleli-community/hackathon/gallery/2026/batch-a/002-SILIKIN10-2015b2f1.jpg"
  },
  {
    "id": "batch-a-51967344",
    "batch": "batch-a",
    "fileName": "SILIKIN11.jpg",
    "thumbUrl": "https://pub-1c80c0f78d1d4fb2bbf1179753cdb92c.r2.dev/mcbuleli-community/hackathon/gallery/2026/batch-a/003-SILIKIN11-51967344.jpg",
    "hdUrl": "https://pub-1c80c0f78d1d4fb2bbf1179753cdb92c.r2.dev/mcbuleli-community/hackathon/gallery/2026/batch-a/003-SILIKIN11-51967344.jpg"
  },
  {
    "id": "batch-a-3957af4d",
    "batch": "batch-a",
    "fileName": "SILIKIN12.jpg",
    "thumbUrl": "https://pub-1c80c0f78d1d4fb2bbf1179753cdb92c.r2.dev/mcbuleli-community/hackathon/gallery/2026/batch-a/004-SILIKIN12-3957af4d.jpg",
    "hdUrl": "https://pub-1c80c0f78d1d4fb2bbf1179753cdb92c.r2.dev/mcbuleli-community/hackathon/gallery/2026/batch-a/004-SILIKIN12-3957af4d.jpg"
  },
  {
    "id": "batch-a-0ed345b5",
    "batch": "batch-a",
    "fileName": "SILIKIN13.jpg",
    "thumbUrl": "https://pub-1c80c0f78d1d4fb2bbf1179753cdb92c.r2.dev/mcbuleli-community/hackathon/gallery/2026/batch-a/005-SILIKIN13-0ed345b5.jpg",
    "hdUrl": "https://pub-1c80c0f78d1d4fb2bbf1179753cdb92c.r2.dev/mcbuleli-community/hackathon/gallery/2026/batch-a/005-SILIKIN13-0ed345b5.jpg"
  },
  {
    "id": "batch-a-00324680",
    "batch": "batch-a",
    "fileName": "SILIKIN14.jpg",
    "thumbUrl": "https://pub-1c80c0f78d1d4fb2bbf1179753cdb92c.r2.dev/mcbuleli-community/hackathon/gallery/2026/batch-a/006-SILIKIN14-00324680.jpg",
    "hdUrl": "https://pub-1c80c0f78d1d4fb2bbf1179753cdb92c.r2.dev/mcbuleli-community/hackathon/gallery/2026/batch-a/006-SILIKIN14-00324680.jpg"
  },
  {
    "id": "batch-a-ebe611e5",
    "batch": "batch-a",
    "fileName": "SILIKIN15.jpg",
    "thumbUrl": "https://pub-1c80c0f78d1d4fb2bbf1179753cdb92c.r2.dev/mcbuleli-community/hackathon/gallery/2026/batch-a/007-SILIKIN15-ebe611e5.jpg",
    "hdUrl": "https://pub-1c80c0f78d1d4fb2bbf1179753cdb92c.r2.dev/mcbuleli-community/hackathon/gallery/2026/batch-a/007-SILIKIN15-ebe611e5.jpg"
  },
  {
    "id": "batch-a-089b4cf4",
    "batch": "batch-a",
    "fileName": "SILIKIN16.jpg",
    "thumbUrl": "https://pub-1c80c0f78d1d4fb2bbf1179753cdb92c.r2.dev/mcbuleli-community/hackathon/gallery/2026/batch-a/008-SILIKIN16-089b4cf4.jpg",
    "hdUrl": "https://pub-1c80c0f78d1d4fb2bbf1179753cdb92c.r2.dev/mcbuleli-community/hackathon/gallery/2026/batch-a/008-SILIKIN16-089b4cf4.jpg"
  },
  {
    "id": "batch-a-c68cf15c",
    "batch": "batch-a",
    "fileName": "SILIKIN17.jpg",
    "thumbUrl": "https://pub-1c80c0f78d1d4fb2bbf1179753cdb92c.r2.dev/mcbuleli-community/hackathon/gallery/2026/batch-a/009-SILIKIN17-c68cf15c.jpg",
    "hdUrl": "https://pub-1c80c0f78d1d4fb2bbf1179753cdb92c.r2.dev/mcbuleli-community/hackathon/gallery/2026/batch-a/009-SILIKIN17-c68cf15c.jpg"
  },
  {
    "id": "batch-a-157f5ee7",
    "batch": "batch-a",
    "fileName": "SILIKIN18.jpg",
    "thumbUrl": "https://pub-1c80c0f78d1d4fb2bbf1179753cdb92c.r2.dev/mcbuleli-community/hackathon/gallery/2026/batch-a/010-SILIKIN18-157f5ee7.jpg",
    "hdUrl": "https://pub-1c80c0f78d1d4fb2bbf1179753cdb92c.r2.dev/mcbuleli-community/hackathon/gallery/2026/batch-a/010-SILIKIN18-157f5ee7.jpg"
  },
  {
    "id": "batch-a-e590cadb",
    "batch": "batch-a",
    "fileName": "SILIKIN19.jpg",
    "thumbUrl": "https://pub-1c80c0f78d1d4fb2bbf1179753cdb92c.r2.dev/mcbuleli-community/hackathon/gallery/2026/batch-a/011-SILIKIN19-e590cadb.jpg",
    "hdUrl": "https://pub-1c80c0f78d1d4fb2bbf1179753cdb92c.r2.dev/mcbuleli-community/hackathon/gallery/2026/batch-a/011-SILIKIN19-e590cadb.jpg"
  },
  {
    "id": "batch-a-973b5471",
    "batch": "batch-a",
    "fileName": "SILIKIN2.jpg",
    "thumbUrl": "https://pub-1c80c0f78d1d4fb2bbf1179753cdb92c.r2.dev/mcbuleli-community/hackathon/gallery/2026/batch-a/012-SILIKIN2-973b5471.jpg",
    "hdUrl": "https://pub-1c80c0f78d1d4fb2bbf1179753cdb92c.r2.dev/mcbuleli-community/hackathon/gallery/2026/batch-a/012-SILIKIN2-973b5471.jpg"
  },
  {
    "id": "batch-a-4a74bb0c",
    "batch": "batch-a",
    "fileName": "SILIKIN20.jpg",
    "thumbUrl": "https://pub-1c80c0f78d1d4fb2bbf1179753cdb92c.r2.dev/mcbuleli-community/hackathon/gallery/2026/batch-a/013-SILIKIN20-4a74bb0c.jpg",
    "hdUrl": "https://pub-1c80c0f78d1d4fb2bbf1179753cdb92c.r2.dev/mcbuleli-community/hackathon/gallery/2026/batch-a/013-SILIKIN20-4a74bb0c.jpg"
  },
  {
    "id": "batch-a-8dd5b66f",
    "batch": "batch-a",
    "fileName": "SILIKIN21.jpg",
    "thumbUrl": "https://pub-1c80c0f78d1d4fb2bbf1179753cdb92c.r2.dev/mcbuleli-community/hackathon/gallery/2026/batch-a/014-SILIKIN21-8dd5b66f.jpg",
    "hdUrl": "https://pub-1c80c0f78d1d4fb2bbf1179753cdb92c.r2.dev/mcbuleli-community/hackathon/gallery/2026/batch-a/014-SILIKIN21-8dd5b66f.jpg"
  },
  {
    "id": "batch-a-28dfcc17",
    "batch": "batch-a",
    "fileName": "SILIKIN22.jpg",
    "thumbUrl": "https://pub-1c80c0f78d1d4fb2bbf1179753cdb92c.r2.dev/mcbuleli-community/hackathon/gallery/2026/batch-a/015-SILIKIN22-28dfcc17.jpg",
    "hdUrl": "https://pub-1c80c0f78d1d4fb2bbf1179753cdb92c.r2.dev/mcbuleli-community/hackathon/gallery/2026/batch-a/015-SILIKIN22-28dfcc17.jpg"
  },
  {
    "id": "batch-a-47f6c9b3",
    "batch": "batch-a",
    "fileName": "SILIKIN23.jpg",
    "thumbUrl": "https://pub-1c80c0f78d1d4fb2bbf1179753cdb92c.r2.dev/mcbuleli-community/hackathon/gallery/2026/batch-a/016-SILIKIN23-47f6c9b3.jpg",
    "hdUrl": "https://pub-1c80c0f78d1d4fb2bbf1179753cdb92c.r2.dev/mcbuleli-community/hackathon/gallery/2026/batch-a/016-SILIKIN23-47f6c9b3.jpg"
  },
  {
    "id": "batch-a-b8010b92",
    "batch": "batch-a",
    "fileName": "SILIKIN24.jpg",
    "thumbUrl": "https://pub-1c80c0f78d1d4fb2bbf1179753cdb92c.r2.dev/mcbuleli-community/hackathon/gallery/2026/batch-a/017-SILIKIN24-b8010b92.jpg",
    "hdUrl": "https://pub-1c80c0f78d1d4fb2bbf1179753cdb92c.r2.dev/mcbuleli-community/hackathon/gallery/2026/batch-a/017-SILIKIN24-b8010b92.jpg"
  },
  {
    "id": "batch-a-31248f5c",
    "batch": "batch-a",
    "fileName": "SILIKIN25.jpg",
    "thumbUrl": "https://pub-1c80c0f78d1d4fb2bbf1179753cdb92c.r2.dev/mcbuleli-community/hackathon/gallery/2026/batch-a/018-SILIKIN25-31248f5c.jpg",
    "hdUrl": "https://pub-1c80c0f78d1d4fb2bbf1179753cdb92c.r2.dev/mcbuleli-community/hackathon/gallery/2026/batch-a/018-SILIKIN25-31248f5c.jpg"
  },
  {
    "id": "batch-a-0ddcbe74",
    "batch": "batch-a",
    "fileName": "SILIKIN26.jpg",
    "thumbUrl": "https://pub-1c80c0f78d1d4fb2bbf1179753cdb92c.r2.dev/mcbuleli-community/hackathon/gallery/2026/batch-a/019-SILIKIN26-0ddcbe74.jpg",
    "hdUrl": "https://pub-1c80c0f78d1d4fb2bbf1179753cdb92c.r2.dev/mcbuleli-community/hackathon/gallery/2026/batch-a/019-SILIKIN26-0ddcbe74.jpg"
  },
  {
    "id": "batch-a-a2fefd82",
    "batch": "batch-a",
    "fileName": "SILIKIN27.jpg",
    "thumbUrl": "https://pub-1c80c0f78d1d4fb2bbf1179753cdb92c.r2.dev/mcbuleli-community/hackathon/gallery/2026/batch-a/020-SILIKIN27-a2fefd82.jpg",
    "hdUrl": "https://pub-1c80c0f78d1d4fb2bbf1179753cdb92c.r2.dev/mcbuleli-community/hackathon/gallery/2026/batch-a/020-SILIKIN27-a2fefd82.jpg"
  },
  {
    "id": "batch-a-59b635e6",
    "batch": "batch-a",
    "fileName": "SILIKIN28.jpg",
    "thumbUrl": "https://pub-1c80c0f78d1d4fb2bbf1179753cdb92c.r2.dev/mcbuleli-community/hackathon/gallery/2026/batch-a/021-SILIKIN28-59b635e6.jpg",
    "hdUrl": "https://pub-1c80c0f78d1d4fb2bbf1179753cdb92c.r2.dev/mcbuleli-community/hackathon/gallery/2026/batch-a/021-SILIKIN28-59b635e6.jpg"
  },
  {
    "id": "batch-a-0e937239",
    "batch": "batch-a",
    "fileName": "SILIKIN29.jpg",
    "thumbUrl": "https://pub-1c80c0f78d1d4fb2bbf1179753cdb92c.r2.dev/mcbuleli-community/hackathon/gallery/2026/batch-a/022-SILIKIN29-0e937239.jpg",
    "hdUrl": "https://pub-1c80c0f78d1d4fb2bbf1179753cdb92c.r2.dev/mcbuleli-community/hackathon/gallery/2026/batch-a/022-SILIKIN29-0e937239.jpg"
  },
  {
    "id": "batch-a-3f23a2c1",
    "batch": "batch-a",
    "fileName": "SILIKIN3.jpg",
    "thumbUrl": "https://pub-1c80c0f78d1d4fb2bbf1179753cdb92c.r2.dev/mcbuleli-community/hackathon/gallery/2026/batch-a/023-SILIKIN3-3f23a2c1.jpg",
    "hdUrl": "https://pub-1c80c0f78d1d4fb2bbf1179753cdb92c.r2.dev/mcbuleli-community/hackathon/gallery/2026/batch-a/023-SILIKIN3-3f23a2c1.jpg"
  },
  {
    "id": "batch-a-c782dd89",
    "batch": "batch-a",
    "fileName": "SILIKIN30.jpg",
    "thumbUrl": "https://pub-1c80c0f78d1d4fb2bbf1179753cdb92c.r2.dev/mcbuleli-community/hackathon/gallery/2026/batch-a/024-SILIKIN30-c782dd89.jpg",
    "hdUrl": "https://pub-1c80c0f78d1d4fb2bbf1179753cdb92c.r2.dev/mcbuleli-community/hackathon/gallery/2026/batch-a/024-SILIKIN30-c782dd89.jpg"
  },
  {
    "id": "batch-a-6ed43eb0",
    "batch": "batch-a",
    "fileName": "SILIKIN31.jpg",
    "thumbUrl": "https://pub-1c80c0f78d1d4fb2bbf1179753cdb92c.r2.dev/mcbuleli-community/hackathon/gallery/2026/batch-a/025-SILIKIN31-6ed43eb0.jpg",
    "hdUrl": "https://pub-1c80c0f78d1d4fb2bbf1179753cdb92c.r2.dev/mcbuleli-community/hackathon/gallery/2026/batch-a/025-SILIKIN31-6ed43eb0.jpg"
  },
  {
    "id": "batch-a-07085c3a",
    "batch": "batch-a",
    "fileName": "SILIKIN32.jpg",
    "thumbUrl": "https://pub-1c80c0f78d1d4fb2bbf1179753cdb92c.r2.dev/mcbuleli-community/hackathon/gallery/2026/batch-a/026-SILIKIN32-07085c3a.jpg",
    "hdUrl": "https://pub-1c80c0f78d1d4fb2bbf1179753cdb92c.r2.dev/mcbuleli-community/hackathon/gallery/2026/batch-a/026-SILIKIN32-07085c3a.jpg"
  },
  {
    "id": "batch-a-caa92710",
    "batch": "batch-a",
    "fileName": "SILIKIN33.jpg",
    "thumbUrl": "https://pub-1c80c0f78d1d4fb2bbf1179753cdb92c.r2.dev/mcbuleli-community/hackathon/gallery/2026/batch-a/027-SILIKIN33-caa92710.jpg",
    "hdUrl": "https://pub-1c80c0f78d1d4fb2bbf1179753cdb92c.r2.dev/mcbuleli-community/hackathon/gallery/2026/batch-a/027-SILIKIN33-caa92710.jpg"
  },
  {
    "id": "batch-a-aec37a80",
    "batch": "batch-a",
    "fileName": "SILIKIN34.JPG",
    "thumbUrl": "https://pub-1c80c0f78d1d4fb2bbf1179753cdb92c.r2.dev/mcbuleli-community/hackathon/gallery/2026/batch-a/028-SILIKIN34-aec37a80.jpg",
    "hdUrl": "https://pub-1c80c0f78d1d4fb2bbf1179753cdb92c.r2.dev/mcbuleli-community/hackathon/gallery/2026/batch-a/028-SILIKIN34-aec37a80.jpg"
  },
  {
    "id": "batch-a-88ab3cc1",
    "batch": "batch-a",
    "fileName": "SILIKIN35.JPG",
    "thumbUrl": "https://pub-1c80c0f78d1d4fb2bbf1179753cdb92c.r2.dev/mcbuleli-community/hackathon/gallery/2026/batch-a/029-SILIKIN35-88ab3cc1.jpg",
    "hdUrl": "https://pub-1c80c0f78d1d4fb2bbf1179753cdb92c.r2.dev/mcbuleli-community/hackathon/gallery/2026/batch-a/029-SILIKIN35-88ab3cc1.jpg"
  },
  {
    "id": "batch-a-9eb76bba",
    "batch": "batch-a",
    "fileName": "SILIKIN36.JPG",
    "thumbUrl": "https://pub-1c80c0f78d1d4fb2bbf1179753cdb92c.r2.dev/mcbuleli-community/hackathon/gallery/2026/batch-a/030-SILIKIN36-9eb76bba.jpg",
    "hdUrl": "https://pub-1c80c0f78d1d4fb2bbf1179753cdb92c.r2.dev/mcbuleli-community/hackathon/gallery/2026/batch-a/030-SILIKIN36-9eb76bba.jpg"
  },
  {
    "id": "batch-a-9950510a",
    "batch": "batch-a",
    "fileName": "SILIKIN37.JPG",
    "thumbUrl": "https://pub-1c80c0f78d1d4fb2bbf1179753cdb92c.r2.dev/mcbuleli-community/hackathon/gallery/2026/batch-a/031-SILIKIN37-9950510a.jpg",
    "hdUrl": "https://pub-1c80c0f78d1d4fb2bbf1179753cdb92c.r2.dev/mcbuleli-community/hackathon/gallery/2026/batch-a/031-SILIKIN37-9950510a.jpg"
  },
  {
    "id": "batch-a-7b09d8e7",
    "batch": "batch-a",
    "fileName": "SILIKIN38.JPG",
    "thumbUrl": "https://pub-1c80c0f78d1d4fb2bbf1179753cdb92c.r2.dev/mcbuleli-community/hackathon/gallery/2026/batch-a/032-SILIKIN38-7b09d8e7.jpg",
    "hdUrl": "https://pub-1c80c0f78d1d4fb2bbf1179753cdb92c.r2.dev/mcbuleli-community/hackathon/gallery/2026/batch-a/032-SILIKIN38-7b09d8e7.jpg"
  },
  {
    "id": "batch-a-5faed3db",
    "batch": "batch-a",
    "fileName": "SILIKIN39.JPG",
    "thumbUrl": "https://pub-1c80c0f78d1d4fb2bbf1179753cdb92c.r2.dev/mcbuleli-community/hackathon/gallery/2026/batch-a/033-SILIKIN39-5faed3db.jpg",
    "hdUrl": "https://pub-1c80c0f78d1d4fb2bbf1179753cdb92c.r2.dev/mcbuleli-community/hackathon/gallery/2026/batch-a/033-SILIKIN39-5faed3db.jpg"
  },
  {
    "id": "batch-a-a0e29135",
    "batch": "batch-a",
    "fileName": "SILIKIN4.jpg",
    "thumbUrl": "https://pub-1c80c0f78d1d4fb2bbf1179753cdb92c.r2.dev/mcbuleli-community/hackathon/gallery/2026/batch-a/034-SILIKIN4-a0e29135.jpg",
    "hdUrl": "https://pub-1c80c0f78d1d4fb2bbf1179753cdb92c.r2.dev/mcbuleli-community/hackathon/gallery/2026/batch-a/034-SILIKIN4-a0e29135.jpg"
  },
  {
    "id": "batch-a-e1c51852",
    "batch": "batch-a",
    "fileName": "SILIKIN40.JPG",
    "thumbUrl": "https://pub-1c80c0f78d1d4fb2bbf1179753cdb92c.r2.dev/mcbuleli-community/hackathon/gallery/2026/batch-a/035-SILIKIN40-e1c51852.jpg",
    "hdUrl": "https://pub-1c80c0f78d1d4fb2bbf1179753cdb92c.r2.dev/mcbuleli-community/hackathon/gallery/2026/batch-a/035-SILIKIN40-e1c51852.jpg"
  },
  {
    "id": "batch-a-9e141fa3",
    "batch": "batch-a",
    "fileName": "SILIKIN41.JPG",
    "thumbUrl": "https://pub-1c80c0f78d1d4fb2bbf1179753cdb92c.r2.dev/mcbuleli-community/hackathon/gallery/2026/batch-a/036-SILIKIN41-9e141fa3.jpg",
    "hdUrl": "https://pub-1c80c0f78d1d4fb2bbf1179753cdb92c.r2.dev/mcbuleli-community/hackathon/gallery/2026/batch-a/036-SILIKIN41-9e141fa3.jpg"
  },
  {
    "id": "batch-a-2e82c801",
    "batch": "batch-a",
    "fileName": "SILIKIN42.JPG",
    "thumbUrl": "https://pub-1c80c0f78d1d4fb2bbf1179753cdb92c.r2.dev/mcbuleli-community/hackathon/gallery/2026/batch-a/037-SILIKIN42-2e82c801.jpg",
    "hdUrl": "https://pub-1c80c0f78d1d4fb2bbf1179753cdb92c.r2.dev/mcbuleli-community/hackathon/gallery/2026/batch-a/037-SILIKIN42-2e82c801.jpg"
  },
  {
    "id": "batch-a-10a9d86a",
    "batch": "batch-a",
    "fileName": "SILIKIN43.JPG",
    "thumbUrl": "https://pub-1c80c0f78d1d4fb2bbf1179753cdb92c.r2.dev/mcbuleli-community/hackathon/gallery/2026/batch-a/038-SILIKIN43-10a9d86a.jpg",
    "hdUrl": "https://pub-1c80c0f78d1d4fb2bbf1179753cdb92c.r2.dev/mcbuleli-community/hackathon/gallery/2026/batch-a/038-SILIKIN43-10a9d86a.jpg"
  },
  {
    "id": "batch-a-6fbd5df0",
    "batch": "batch-a",
    "fileName": "SILIKIN44.JPG",
    "thumbUrl": "https://pub-1c80c0f78d1d4fb2bbf1179753cdb92c.r2.dev/mcbuleli-community/hackathon/gallery/2026/batch-a/039-SILIKIN44-6fbd5df0.jpg",
    "hdUrl": "https://pub-1c80c0f78d1d4fb2bbf1179753cdb92c.r2.dev/mcbuleli-community/hackathon/gallery/2026/batch-a/039-SILIKIN44-6fbd5df0.jpg"
  },
  {
    "id": "batch-a-ffe4b26d",
    "batch": "batch-a",
    "fileName": "SILIKIN45.JPG",
    "thumbUrl": "https://pub-1c80c0f78d1d4fb2bbf1179753cdb92c.r2.dev/mcbuleli-community/hackathon/gallery/2026/batch-a/040-SILIKIN45-ffe4b26d.jpg",
    "hdUrl": "https://pub-1c80c0f78d1d4fb2bbf1179753cdb92c.r2.dev/mcbuleli-community/hackathon/gallery/2026/batch-a/040-SILIKIN45-ffe4b26d.jpg"
  },
  {
    "id": "batch-a-d7fd120d",
    "batch": "batch-a",
    "fileName": "SILIKIN46.JPG",
    "thumbUrl": "https://pub-1c80c0f78d1d4fb2bbf1179753cdb92c.r2.dev/mcbuleli-community/hackathon/gallery/2026/batch-a/041-SILIKIN46-d7fd120d.jpg",
    "hdUrl": "https://pub-1c80c0f78d1d4fb2bbf1179753cdb92c.r2.dev/mcbuleli-community/hackathon/gallery/2026/batch-a/041-SILIKIN46-d7fd120d.jpg"
  },
  {
    "id": "batch-a-2b5ae161",
    "batch": "batch-a",
    "fileName": "SILIKIN47.JPG",
    "thumbUrl": "https://pub-1c80c0f78d1d4fb2bbf1179753cdb92c.r2.dev/mcbuleli-community/hackathon/gallery/2026/batch-a/042-SILIKIN47-2b5ae161.jpg",
    "hdUrl": "https://pub-1c80c0f78d1d4fb2bbf1179753cdb92c.r2.dev/mcbuleli-community/hackathon/gallery/2026/batch-a/042-SILIKIN47-2b5ae161.jpg"
  },
  {
    "id": "batch-a-eb7ee2a8",
    "batch": "batch-a",
    "fileName": "SILIKIN48.JPG",
    "thumbUrl": "https://pub-1c80c0f78d1d4fb2bbf1179753cdb92c.r2.dev/mcbuleli-community/hackathon/gallery/2026/batch-a/043-SILIKIN48-eb7ee2a8.jpg",
    "hdUrl": "https://pub-1c80c0f78d1d4fb2bbf1179753cdb92c.r2.dev/mcbuleli-community/hackathon/gallery/2026/batch-a/043-SILIKIN48-eb7ee2a8.jpg"
  },
  {
    "id": "batch-a-3b76e660",
    "batch": "batch-a",
    "fileName": "SILIKIN49.JPG",
    "thumbUrl": "https://pub-1c80c0f78d1d4fb2bbf1179753cdb92c.r2.dev/mcbuleli-community/hackathon/gallery/2026/batch-a/044-SILIKIN49-3b76e660.jpg",
    "hdUrl": "https://pub-1c80c0f78d1d4fb2bbf1179753cdb92c.r2.dev/mcbuleli-community/hackathon/gallery/2026/batch-a/044-SILIKIN49-3b76e660.jpg"
  },
  {
    "id": "batch-a-8ac14360",
    "batch": "batch-a",
    "fileName": "SILIKIN5.jpg",
    "thumbUrl": "https://pub-1c80c0f78d1d4fb2bbf1179753cdb92c.r2.dev/mcbuleli-community/hackathon/gallery/2026/batch-a/045-SILIKIN5-8ac14360.jpg",
    "hdUrl": "https://pub-1c80c0f78d1d4fb2bbf1179753cdb92c.r2.dev/mcbuleli-community/hackathon/gallery/2026/batch-a/045-SILIKIN5-8ac14360.jpg"
  },
  {
    "id": "batch-a-6b319493",
    "batch": "batch-a",
    "fileName": "SILIKIN50.JPG",
    "thumbUrl": "https://pub-1c80c0f78d1d4fb2bbf1179753cdb92c.r2.dev/mcbuleli-community/hackathon/gallery/2026/batch-a/046-SILIKIN50-6b319493.jpg",
    "hdUrl": "https://pub-1c80c0f78d1d4fb2bbf1179753cdb92c.r2.dev/mcbuleli-community/hackathon/gallery/2026/batch-a/046-SILIKIN50-6b319493.jpg"
  },
  {
    "id": "batch-a-73d5d91b",
    "batch": "batch-a",
    "fileName": "SILIKIN51.JPG",
    "thumbUrl": "https://pub-1c80c0f78d1d4fb2bbf1179753cdb92c.r2.dev/mcbuleli-community/hackathon/gallery/2026/batch-a/047-SILIKIN51-73d5d91b.jpg",
    "hdUrl": "https://pub-1c80c0f78d1d4fb2bbf1179753cdb92c.r2.dev/mcbuleli-community/hackathon/gallery/2026/batch-a/047-SILIKIN51-73d5d91b.jpg"
  },
  {
    "id": "batch-a-00ed6ee4",
    "batch": "batch-a",
    "fileName": "SILIKIN52.JPG",
    "thumbUrl": "https://pub-1c80c0f78d1d4fb2bbf1179753cdb92c.r2.dev/mcbuleli-community/hackathon/gallery/2026/batch-a/048-SILIKIN52-00ed6ee4.jpg",
    "hdUrl": "https://pub-1c80c0f78d1d4fb2bbf1179753cdb92c.r2.dev/mcbuleli-community/hackathon/gallery/2026/batch-a/048-SILIKIN52-00ed6ee4.jpg"
  },
  {
    "id": "batch-a-f6a223a8",
    "batch": "batch-a",
    "fileName": "SILIKIN53.JPG",
    "thumbUrl": "https://pub-1c80c0f78d1d4fb2bbf1179753cdb92c.r2.dev/mcbuleli-community/hackathon/gallery/2026/batch-a/049-SILIKIN53-f6a223a8.jpg",
    "hdUrl": "https://pub-1c80c0f78d1d4fb2bbf1179753cdb92c.r2.dev/mcbuleli-community/hackathon/gallery/2026/batch-a/049-SILIKIN53-f6a223a8.jpg"
  },
  {
    "id": "batch-a-e38679ca",
    "batch": "batch-a",
    "fileName": "SILIKIN54.JPG",
    "thumbUrl": "https://pub-1c80c0f78d1d4fb2bbf1179753cdb92c.r2.dev/mcbuleli-community/hackathon/gallery/2026/batch-a/050-SILIKIN54-e38679ca.jpg",
    "hdUrl": "https://pub-1c80c0f78d1d4fb2bbf1179753cdb92c.r2.dev/mcbuleli-community/hackathon/gallery/2026/batch-a/050-SILIKIN54-e38679ca.jpg"
  },
  {
    "id": "batch-a-2e4a4598",
    "batch": "batch-a",
    "fileName": "SILIKIN55.JPG",
    "thumbUrl": "https://pub-1c80c0f78d1d4fb2bbf1179753cdb92c.r2.dev/mcbuleli-community/hackathon/gallery/2026/batch-a/051-SILIKIN55-2e4a4598.jpg",
    "hdUrl": "https://pub-1c80c0f78d1d4fb2bbf1179753cdb92c.r2.dev/mcbuleli-community/hackathon/gallery/2026/batch-a/051-SILIKIN55-2e4a4598.jpg"
  },
  {
    "id": "batch-a-ae1ea1e6",
    "batch": "batch-a",
    "fileName": "SILIKIN56.JPG",
    "thumbUrl": "https://pub-1c80c0f78d1d4fb2bbf1179753cdb92c.r2.dev/mcbuleli-community/hackathon/gallery/2026/batch-a/052-SILIKIN56-ae1ea1e6.jpg",
    "hdUrl": "https://pub-1c80c0f78d1d4fb2bbf1179753cdb92c.r2.dev/mcbuleli-community/hackathon/gallery/2026/batch-a/052-SILIKIN56-ae1ea1e6.jpg"
  },
  {
    "id": "batch-a-cb480fe3",
    "batch": "batch-a",
    "fileName": "SILIKIN57.JPG",
    "thumbUrl": "https://pub-1c80c0f78d1d4fb2bbf1179753cdb92c.r2.dev/mcbuleli-community/hackathon/gallery/2026/batch-a/053-SILIKIN57-cb480fe3.jpg",
    "hdUrl": "https://pub-1c80c0f78d1d4fb2bbf1179753cdb92c.r2.dev/mcbuleli-community/hackathon/gallery/2026/batch-a/053-SILIKIN57-cb480fe3.jpg"
  },
  {
    "id": "batch-a-3d5809fa",
    "batch": "batch-a",
    "fileName": "SILIKIN58.JPG",
    "thumbUrl": "https://pub-1c80c0f78d1d4fb2bbf1179753cdb92c.r2.dev/mcbuleli-community/hackathon/gallery/2026/batch-a/054-SILIKIN58-3d5809fa.jpg",
    "hdUrl": "https://pub-1c80c0f78d1d4fb2bbf1179753cdb92c.r2.dev/mcbuleli-community/hackathon/gallery/2026/batch-a/054-SILIKIN58-3d5809fa.jpg"
  },
  {
    "id": "batch-a-16735e83",
    "batch": "batch-a",
    "fileName": "SILIKIN59.JPG",
    "thumbUrl": "https://pub-1c80c0f78d1d4fb2bbf1179753cdb92c.r2.dev/mcbuleli-community/hackathon/gallery/2026/batch-a/055-SILIKIN59-16735e83.jpg",
    "hdUrl": "https://pub-1c80c0f78d1d4fb2bbf1179753cdb92c.r2.dev/mcbuleli-community/hackathon/gallery/2026/batch-a/055-SILIKIN59-16735e83.jpg"
  },
  {
    "id": "batch-a-df9835c7",
    "batch": "batch-a",
    "fileName": "SILIKIN6.jpg",
    "thumbUrl": "https://pub-1c80c0f78d1d4fb2bbf1179753cdb92c.r2.dev/mcbuleli-community/hackathon/gallery/2026/batch-a/056-SILIKIN6-df9835c7.jpg",
    "hdUrl": "https://pub-1c80c0f78d1d4fb2bbf1179753cdb92c.r2.dev/mcbuleli-community/hackathon/gallery/2026/batch-a/056-SILIKIN6-df9835c7.jpg"
  },
  {
    "id": "batch-a-4c1613d3",
    "batch": "batch-a",
    "fileName": "SILIKIN60.JPG",
    "thumbUrl": "https://pub-1c80c0f78d1d4fb2bbf1179753cdb92c.r2.dev/mcbuleli-community/hackathon/gallery/2026/batch-a/057-SILIKIN60-4c1613d3.jpg",
    "hdUrl": "https://pub-1c80c0f78d1d4fb2bbf1179753cdb92c.r2.dev/mcbuleli-community/hackathon/gallery/2026/batch-a/057-SILIKIN60-4c1613d3.jpg"
  },
  {
    "id": "batch-a-d728b0e7",
    "batch": "batch-a",
    "fileName": "SILIKIN61.JPG",
    "thumbUrl": "https://pub-1c80c0f78d1d4fb2bbf1179753cdb92c.r2.dev/mcbuleli-community/hackathon/gallery/2026/batch-a/058-SILIKIN61-d728b0e7.jpg",
    "hdUrl": "https://pub-1c80c0f78d1d4fb2bbf1179753cdb92c.r2.dev/mcbuleli-community/hackathon/gallery/2026/batch-a/058-SILIKIN61-d728b0e7.jpg"
  },
  {
    "id": "batch-a-5ad16bb5",
    "batch": "batch-a",
    "fileName": "SILIKIN62.JPG",
    "thumbUrl": "https://pub-1c80c0f78d1d4fb2bbf1179753cdb92c.r2.dev/mcbuleli-community/hackathon/gallery/2026/batch-a/059-SILIKIN62-5ad16bb5.jpg",
    "hdUrl": "https://pub-1c80c0f78d1d4fb2bbf1179753cdb92c.r2.dev/mcbuleli-community/hackathon/gallery/2026/batch-a/059-SILIKIN62-5ad16bb5.jpg"
  },
  {
    "id": "batch-a-bc8201b1",
    "batch": "batch-a",
    "fileName": "SILIKIN63.JPG",
    "thumbUrl": "https://pub-1c80c0f78d1d4fb2bbf1179753cdb92c.r2.dev/mcbuleli-community/hackathon/gallery/2026/batch-a/060-SILIKIN63-bc8201b1.jpg",
    "hdUrl": "https://pub-1c80c0f78d1d4fb2bbf1179753cdb92c.r2.dev/mcbuleli-community/hackathon/gallery/2026/batch-a/060-SILIKIN63-bc8201b1.jpg"
  },
  {
    "id": "batch-a-29edb9d4",
    "batch": "batch-a",
    "fileName": "SILIKIN64.JPG",
    "thumbUrl": "https://pub-1c80c0f78d1d4fb2bbf1179753cdb92c.r2.dev/mcbuleli-community/hackathon/gallery/2026/batch-a/061-SILIKIN64-29edb9d4.jpg",
    "hdUrl": "https://pub-1c80c0f78d1d4fb2bbf1179753cdb92c.r2.dev/mcbuleli-community/hackathon/gallery/2026/batch-a/061-SILIKIN64-29edb9d4.jpg"
  },
  {
    "id": "batch-a-3aa0bcbf",
    "batch": "batch-a",
    "fileName": "SILIKIN65.JPG",
    "thumbUrl": "https://pub-1c80c0f78d1d4fb2bbf1179753cdb92c.r2.dev/mcbuleli-community/hackathon/gallery/2026/batch-a/062-SILIKIN65-3aa0bcbf.jpg",
    "hdUrl": "https://pub-1c80c0f78d1d4fb2bbf1179753cdb92c.r2.dev/mcbuleli-community/hackathon/gallery/2026/batch-a/062-SILIKIN65-3aa0bcbf.jpg"
  },
  {
    "id": "batch-a-75bd60d0",
    "batch": "batch-a",
    "fileName": "SILIKIN66.JPG",
    "thumbUrl": "https://pub-1c80c0f78d1d4fb2bbf1179753cdb92c.r2.dev/mcbuleli-community/hackathon/gallery/2026/batch-a/063-SILIKIN66-75bd60d0.jpg",
    "hdUrl": "https://pub-1c80c0f78d1d4fb2bbf1179753cdb92c.r2.dev/mcbuleli-community/hackathon/gallery/2026/batch-a/063-SILIKIN66-75bd60d0.jpg"
  },
  {
    "id": "batch-a-6eed3745",
    "batch": "batch-a",
    "fileName": "SILIKIN67.JPG",
    "thumbUrl": "https://pub-1c80c0f78d1d4fb2bbf1179753cdb92c.r2.dev/mcbuleli-community/hackathon/gallery/2026/batch-a/064-SILIKIN67-6eed3745.jpg",
    "hdUrl": "https://pub-1c80c0f78d1d4fb2bbf1179753cdb92c.r2.dev/mcbuleli-community/hackathon/gallery/2026/batch-a/064-SILIKIN67-6eed3745.jpg"
  },
  {
    "id": "batch-a-a992d6fb",
    "batch": "batch-a",
    "fileName": "SILIKIN68.JPG",
    "thumbUrl": "https://pub-1c80c0f78d1d4fb2bbf1179753cdb92c.r2.dev/mcbuleli-community/hackathon/gallery/2026/batch-a/065-SILIKIN68-a992d6fb.jpg",
    "hdUrl": "https://pub-1c80c0f78d1d4fb2bbf1179753cdb92c.r2.dev/mcbuleli-community/hackathon/gallery/2026/batch-a/065-SILIKIN68-a992d6fb.jpg"
  },
  {
    "id": "batch-a-d7fd03cb",
    "batch": "batch-a",
    "fileName": "SILIKIN69.JPG",
    "thumbUrl": "https://pub-1c80c0f78d1d4fb2bbf1179753cdb92c.r2.dev/mcbuleli-community/hackathon/gallery/2026/batch-a/066-SILIKIN69-d7fd03cb.jpg",
    "hdUrl": "https://pub-1c80c0f78d1d4fb2bbf1179753cdb92c.r2.dev/mcbuleli-community/hackathon/gallery/2026/batch-a/066-SILIKIN69-d7fd03cb.jpg"
  },
  {
    "id": "batch-a-72de7760",
    "batch": "batch-a",
    "fileName": "SILIKIN7.jpg",
    "thumbUrl": "https://pub-1c80c0f78d1d4fb2bbf1179753cdb92c.r2.dev/mcbuleli-community/hackathon/gallery/2026/batch-a/067-SILIKIN7-72de7760.jpg",
    "hdUrl": "https://pub-1c80c0f78d1d4fb2bbf1179753cdb92c.r2.dev/mcbuleli-community/hackathon/gallery/2026/batch-a/067-SILIKIN7-72de7760.jpg"
  },
  {
    "id": "batch-a-30b1e0a7",
    "batch": "batch-a",
    "fileName": "SILIKIN70.JPG",
    "thumbUrl": "https://pub-1c80c0f78d1d4fb2bbf1179753cdb92c.r2.dev/mcbuleli-community/hackathon/gallery/2026/batch-a/068-SILIKIN70-30b1e0a7.jpg",
    "hdUrl": "https://pub-1c80c0f78d1d4fb2bbf1179753cdb92c.r2.dev/mcbuleli-community/hackathon/gallery/2026/batch-a/068-SILIKIN70-30b1e0a7.jpg"
  },
  {
    "id": "batch-a-41492598",
    "batch": "batch-a",
    "fileName": "SILIKIN71.JPG",
    "thumbUrl": "https://pub-1c80c0f78d1d4fb2bbf1179753cdb92c.r2.dev/mcbuleli-community/hackathon/gallery/2026/batch-a/069-SILIKIN71-41492598.jpg",
    "hdUrl": "https://pub-1c80c0f78d1d4fb2bbf1179753cdb92c.r2.dev/mcbuleli-community/hackathon/gallery/2026/batch-a/069-SILIKIN71-41492598.jpg"
  },
  {
    "id": "batch-a-caa5b8cd",
    "batch": "batch-a",
    "fileName": "SILIKIN72.JPG",
    "thumbUrl": "https://pub-1c80c0f78d1d4fb2bbf1179753cdb92c.r2.dev/mcbuleli-community/hackathon/gallery/2026/batch-a/070-SILIKIN72-caa5b8cd.jpg",
    "hdUrl": "https://pub-1c80c0f78d1d4fb2bbf1179753cdb92c.r2.dev/mcbuleli-community/hackathon/gallery/2026/batch-a/070-SILIKIN72-caa5b8cd.jpg"
  },
  {
    "id": "batch-a-45459ba2",
    "batch": "batch-a",
    "fileName": "SILIKIN73.JPG",
    "thumbUrl": "https://pub-1c80c0f78d1d4fb2bbf1179753cdb92c.r2.dev/mcbuleli-community/hackathon/gallery/2026/batch-a/071-SILIKIN73-45459ba2.jpg",
    "hdUrl": "https://pub-1c80c0f78d1d4fb2bbf1179753cdb92c.r2.dev/mcbuleli-community/hackathon/gallery/2026/batch-a/071-SILIKIN73-45459ba2.jpg"
  },
  {
    "id": "batch-a-fab27bd8",
    "batch": "batch-a",
    "fileName": "SILIKIN74.JPG",
    "thumbUrl": "https://pub-1c80c0f78d1d4fb2bbf1179753cdb92c.r2.dev/mcbuleli-community/hackathon/gallery/2026/batch-a/072-SILIKIN74-fab27bd8.jpg",
    "hdUrl": "https://pub-1c80c0f78d1d4fb2bbf1179753cdb92c.r2.dev/mcbuleli-community/hackathon/gallery/2026/batch-a/072-SILIKIN74-fab27bd8.jpg"
  },
  {
    "id": "batch-a-96bc0f0a",
    "batch": "batch-a",
    "fileName": "SILIKIN75.JPG",
    "thumbUrl": "https://pub-1c80c0f78d1d4fb2bbf1179753cdb92c.r2.dev/mcbuleli-community/hackathon/gallery/2026/batch-a/073-SILIKIN75-96bc0f0a.jpg",
    "hdUrl": "https://pub-1c80c0f78d1d4fb2bbf1179753cdb92c.r2.dev/mcbuleli-community/hackathon/gallery/2026/batch-a/073-SILIKIN75-96bc0f0a.jpg"
  },
  {
    "id": "batch-a-3240faa7",
    "batch": "batch-a",
    "fileName": "SILIKIN8.jpg",
    "thumbUrl": "https://pub-1c80c0f78d1d4fb2bbf1179753cdb92c.r2.dev/mcbuleli-community/hackathon/gallery/2026/batch-a/074-SILIKIN8-3240faa7.jpg",
    "hdUrl": "https://pub-1c80c0f78d1d4fb2bbf1179753cdb92c.r2.dev/mcbuleli-community/hackathon/gallery/2026/batch-a/074-SILIKIN8-3240faa7.jpg"
  },
  {
    "id": "batch-a-3405ad94",
    "batch": "batch-a",
    "fileName": "SILIKIN9.jpg",
    "thumbUrl": "https://pub-1c80c0f78d1d4fb2bbf1179753cdb92c.r2.dev/mcbuleli-community/hackathon/gallery/2026/batch-a/075-SILIKIN9-3405ad94.jpg",
    "hdUrl": "https://pub-1c80c0f78d1d4fb2bbf1179753cdb92c.r2.dev/mcbuleli-community/hackathon/gallery/2026/batch-a/075-SILIKIN9-3405ad94.jpg"
  }
];

export const HACKATHON_GALLERY_READY = HACKATHON_GALLERY_PHOTOS.length > 0;
